import {
  EventCategory,
  EventPublic,
  EventStatus,
  EventType,
  EventStage,
  EventFaq,
  UserPublic,
  UserRole,
} from '@hackers-unity/shared-types';

export interface ExtendedEvent extends EventPublic {
  tags: string[];
  bannerGradient: string;
  organizerName: string;
  organizerAvatar: string;
  totalPrizeValue: number;
  participantsCount: number;
  featured?: boolean;
  stages: EventStage[];
  faqs: EventFaq[];
  tracks: { title: string; prize: string; description: string }[];
  sponsors: { name: string; tier: string; logoText: string }[];
}

export interface ExtendedHacker extends UserPublic {
  title: string;
  rating: number;
  hackathonsWon: number;
  openForTeams: boolean;
  interests: string[];
}

export const MOCK_EVENTS: ExtendedEvent[] = [
  {
    id: 'evt_1',
    organizerId: 'org_1',
    organizerName: 'Nexus AI Foundation',
    organizerAvatar: '⚡',
    title: 'AI Nexus Global Hackathon 2026',
    slug: 'ai-nexus-global-2026',
    description:
      'Build the next frontier of Autonomous Multi-Agent Systems, Cognitive Neural Networks, and Real-time Voice/Vision Agents. Compete with 5,000+ builders worldwide with direct venture funding tracks.',
    category: EventCategory.HACKATHON,
    eventType: EventType.ONLINE,
    startDate: '2026-09-01T00:00:00Z',
    endDate: '2026-09-15T23:59:59Z',
    registrationDeadline: '2026-08-31T23:59:59Z',
    eligibilityRules: {
      minAge: 16,
      openGlobally: true,
      allowedTools: 'Any open-source model, proprietary API, or custom architecture',
    },
    prizes: [
      { position: '🥇 1st Grand Prize', amount: 35000, description: 'Cash grant + Seed round intros + GPU cluster credits' },
      { position: '🥈 2nd Prize', amount: 15000, description: 'Cash grant + Tier-1 Accelerator interview fast-track' },
      { position: '🥉 3rd Prize', amount: 10000, description: 'Cash grant + Cloud infra credits' },
      { position: '🌟 Best Agentic Architecture', amount: 5000, description: 'Sponsored by Anthropic & Gemini teams' },
    ],
    totalPrizeValue: 65000,
    bannerUrl: null,
    rulesDocUrl: 'https://hackersunity.dev/rules/ai-nexus',
    status: EventStatus.PUBLISHED,
    maxParticipants: 10000,
    minTeamSize: 1,
    maxTeamSize: 4,
    isTeamEvent: true,
    location: 'Virtual / Discord & Global Stream',
    createdAt: '2026-08-01T10:00:00Z',
    participantsCount: 3420,
    featured: true,
    tags: ['GenAI', 'Autonomous Agents', 'LLMs', 'PyTorch', 'Next.js'],
    bannerGradient: 'from-cyan-900/60 via-blue-950/80 to-black',
    tracks: [
      {
        title: 'Autonomous Coding & DevTools',
        prize: '$20,000 Pool',
        description: 'Build agents that debug, refactor, auto-test, and deploy high-concurrency production systems.',
      },
      {
        title: 'Multimodal Spatial & Voice Intelligence',
        prize: '$15,000 Pool',
        description: 'Create zero-latency conversational workflows with real-time video stream interpretation.',
      },
      {
        title: 'Decentralized AI & On-Chain Inference',
        prize: '$15,000 Pool',
        description: 'Verifiable inference, zero-knowledge proofs for model training, and decentralized compute sharing.',
      },
    ],
    stages: [
      {
        id: 'stg_1',
        eventId: 'evt_1',
        stageName: 'Registration & Team Formation',
        stageOrder: 1,
        startDate: '2026-08-10T00:00:00Z',
        endDate: '2026-08-31T23:59:59Z',
        description: 'Form teams up to 4 members or go solo. Join matching mixers on Hackers Unity.',
      },
      {
        id: 'stg_2',
        eventId: 'evt_1',
        stageName: 'Hacking & Midpoint Review',
        stageOrder: 2,
        startDate: '2026-09-01T00:00:00Z',
        endDate: '2026-09-10T23:59:59Z',
        description: 'Build your prototype, attend live mentor sessions, and submit draft progress.',
      },
      {
        id: 'stg_3',
        eventId: 'evt_1',
        stageName: 'Final Submissions & Live Pitching',
        stageOrder: 3,
        startDate: '2026-09-11T00:00:00Z',
        endDate: '2026-09-15T23:59:59Z',
        description: 'Top 10 finalist teams pitch live to VC partners and industry leaders.',
      },
    ],
    faqs: [
      {
        id: 'faq_1',
        eventId: 'evt_1',
        question: 'Can I participate if I am a beginner?',
        answer: 'Yes! We have beginner-friendly starter kits, workshops, and dedicated technical mentors in our Discord channel.',
        createdAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'faq_2',
        eventId: 'evt_1',
        question: 'How are teams formed and managed?',
        answer: 'You can use the Hackers Unity "Find Teammates" matchmaker or invite your friends directly via email/invite links.',
        createdAt: '2026-08-01T10:00:00Z',
      },
      {
        id: 'faq_3',
        eventId: 'evt_1',
        question: 'Are there API credits provided?',
        answer: 'All verified participants receive $200 worth of model and compute API credits upon check-in.',
        createdAt: '2026-08-01T10:00:00Z',
      },
    ],
    sponsors: [
      { name: 'Google Cloud', tier: 'Title Partner', logoText: 'CLOUD' },
      { name: 'Vercel', tier: 'Infra Partner', logoText: 'VERCEL' },
      { name: 'NVIDIA Inception', tier: 'Compute Partner', logoText: 'NVIDIA' },
      { name: 'Supabase', tier: 'Database Partner', logoText: 'SUPABASE' },
    ],
  },
  {
    id: 'evt_2',
    organizerId: 'org_2',
    organizerName: 'Ethereum Builders Guild',
    organizerAvatar: '🔷',
    title: 'Web3 Zero-Knowledge Sprint 2026',
    slug: 'web3-zk-sprint-2026',
    description:
      'Pioneer the next wave of zk-SNARKs, Account Abstraction, and privacy-preserving decentralized finance primitives. Direct grants and testnet launch sponsorship included.',
    category: EventCategory.HACKATHON,
    eventType: EventType.HYBRID,
    startDate: '2026-09-10T09:00:00Z',
    endDate: '2026-09-20T18:00:00Z',
    registrationDeadline: '2026-09-08T23:59:59Z',
    eligibilityRules: { minAge: 18, openGlobally: true },
    prizes: [
      { position: '🥇 Champion', amount: 25000, description: 'Grant + Audit credits from CertiK' },
      { position: '🥈 Runner Up', amount: 12000, description: 'Ecosystem grant' },
      { position: '🥉 Third Place', amount: 8000, description: 'Ecosystem grant' },
      { position: '🛡️ Best ZK Privacy Tool', amount: 5000, description: 'Special sponsor track' },
    ],
    totalPrizeValue: 50000,
    bannerUrl: null,
    rulesDocUrl: 'https://hackersunity.dev/rules/zk-sprint',
    status: EventStatus.PUBLISHED,
    maxParticipants: 3000,
    minTeamSize: 1,
    maxTeamSize: 5,
    isTeamEvent: true,
    location: 'Bangalore Innovation Hub & Online Hybrid',
    createdAt: '2026-08-05T10:00:00Z',
    participantsCount: 1840,
    featured: true,
    tags: ['Web3', 'ZK-Proofs', 'Rust', 'Solidity', 'DeFi'],
    bannerGradient: 'from-purple-950/70 via-indigo-950/80 to-black',
    tracks: [
      { title: 'ZK Identity & Authentication', prize: '$15,000 Pool', description: 'Zero-knowledge KYC and decentralized trust systems.' },
      { title: 'Scalable L2 Rollups & Bridges', prize: '$15,000 Pool', description: 'Cross-rollup verification and fast finality algorithms.' },
      { title: 'Privacy DeFi & MEV Resistance', prize: '$10,000 Pool', description: 'Private transaction routing and fair sequencer designs.' },
    ],
    stages: [
      { id: 'stg_21', eventId: 'evt_2', stageName: 'Kickoff & Ideation', stageOrder: 1, startDate: '2026-09-10T09:00:00Z', endDate: '2026-09-12T23:59:59Z', description: 'Problem statements released' },
      { id: 'stg_22', eventId: 'evt_2', stageName: 'Build Phase', stageOrder: 2, startDate: '2026-09-13T00:00:00Z', endDate: '2026-09-18T23:59:59Z', description: 'Smart contract deployment on testnets' },
      { id: 'stg_23', eventId: 'evt_2', stageName: 'Demo Day & Finals', stageOrder: 3, startDate: '2026-09-19T00:00:00Z', endDate: '2026-09-20T18:00:00Z', description: 'Judges test live contracts' },
    ],
    faqs: [
      { id: 'faq_21', eventId: 'evt_2', question: 'Do I need prior ZK-proof experience?', answer: 'Basic knowledge of Rust or Noir helps, but we run 3 pre-event bootcamps.', createdAt: '2026-08-05T10:00:00Z' },
    ],
    sponsors: [
      { name: 'Polygon', tier: 'L2 Partner', logoText: 'POLYGON' },
      { name: 'Starknet', tier: 'ZK Partner', logoText: 'STARKNET' },
      { name: 'Chainlink', tier: 'Oracle Partner', logoText: 'CHAINLINK' },
    ],
  },
  {
    id: 'evt_3',
    organizerId: 'org_3',
    organizerName: 'Quantum Cloud Collective',
    organizerAvatar: '⚛️',
    title: 'CyberShield DEFCON Open Hackathon',
    slug: 'cybershield-defcon-2026',
    description:
      'Test your defensive and offensive cybersecurity skills. Build AI-driven intrusion detection systems, malware honeypots, automated vulnerability scanners, and cryptographic guardrails.',
    category: EventCategory.COMPETITION,
    eventType: EventType.ONLINE,
    startDate: '2026-08-25T00:00:00Z',
    endDate: '2026-09-05T23:59:59Z',
    registrationDeadline: '2026-08-24T18:00:00Z',
    eligibilityRules: { ethicalPledgeRequired: true },
    prizes: [
      { position: '🥇 Grand Defender', amount: 20000, description: 'Cash + Certified Pen-Testing Sponsorship' },
      { position: '🥈 Runner Up', amount: 10000, description: 'Cash grant' },
      { position: '🥉 Third Place', amount: 5000, description: 'Cash grant' },
    ],
    totalPrizeValue: 35000,
    bannerUrl: null,
    rulesDocUrl: 'https://hackersunity.dev/rules/cybershield',
    status: EventStatus.ONGOING,
    maxParticipants: 4000,
    minTeamSize: 1,
    maxTeamSize: 3,
    isTeamEvent: true,
    location: 'Cyber Sandbox / Global',
    createdAt: '2026-07-28T10:00:00Z',
    participantsCount: 2210,
    featured: true,
    tags: ['Cybersecurity', 'Reverse Engineering', 'AI Defenses', 'Go', 'Linux'],
    bannerGradient: 'from-emerald-950/70 via-teal-950/80 to-black',
    tracks: [
      { title: 'AI Red Teaming Tools', prize: '$12,000 Pool', description: 'Automated jailbreak detectors and guardrail stress testers.' },
      { title: 'Cloud Infrastructure SecOps', prize: '$10,000 Pool', description: 'Kubernetes runtime defense and zero-trust IAM analyzers.' },
    ],
    stages: [
      { id: 'stg_31', eventId: 'evt_3', stageName: 'CTF Warmup', stageOrder: 1, startDate: '2026-08-25T00:00:00Z', endDate: '2026-08-28T23:59:59Z', description: 'Scored CTF challenges' },
      { id: 'stg_32', eventId: 'evt_3', stageName: 'Tool Build Phase', stageOrder: 2, startDate: '2026-08-29T00:00:00Z', endDate: '2026-09-05T23:59:59Z', description: 'Deliver working open-source security tool' },
    ],
    faqs: [
      { id: 'faq_31', eventId: 'evt_3', question: 'Is offensive tool creation allowed?', answer: 'Only strictly educational and defense verification tools compliant with ethical guidelines.', createdAt: '2026-07-28T10:00:00Z' },
    ],
    sponsors: [
      { name: 'CrowdStrike', tier: 'Security Partner', logoText: 'CROWDSTRIKE' },
      { name: 'Cloudflare', tier: 'Edge Partner', logoText: 'CLOUDFLARE' },
    ],
  },
  {
    id: 'evt_4',
    organizerId: 'org_4',
    organizerName: 'DevCommunity Global',
    organizerAvatar: '🚀',
    title: 'Fullstack Next.js 16 Rapid Sprint',
    slug: 'nextjs-16-rapid-sprint',
    description:
      'Ship full-stack production-ready applications with Server Components, Turbopack, Streaming AI UI, and Edge databases in 48 hours.',
    category: EventCategory.HACKATHON,
    eventType: EventType.ONLINE,
    startDate: '2026-09-05T00:00:00Z',
    endDate: '2026-09-07T23:59:59Z',
    registrationDeadline: '2026-09-04T12:00:00Z',
    eligibilityRules: null,
    prizes: [
      { position: '🥇 Best Production App', amount: 10000, description: 'Cash + M4 Pro MacBook' },
      { position: '🥈 Runner Up', amount: 5000, description: 'Cash + Vercel Enterprise 1yr' },
      { position: '🥉 Third Place', amount: 2500, description: 'Cash + Swag Pack' },
    ],
    totalPrizeValue: 17500,
    bannerUrl: null,
    rulesDocUrl: null,
    status: EventStatus.PUBLISHED,
    maxParticipants: 5000,
    minTeamSize: 1,
    maxTeamSize: 4,
    isTeamEvent: true,
    location: 'Online',
    createdAt: '2026-08-10T12:00:00Z',
    participantsCount: 1450,
    featured: false,
    tags: ['React 19', 'Next.js', 'TailwindCSS', 'TypeScript', 'Prisma'],
    bannerGradient: 'from-zinc-900 via-zinc-950 to-black',
    tracks: [
      { title: 'SaaS in 48 Hours', prize: '$7,500', description: 'Monetizable micro-SaaS with authentication and billing.' },
      { title: 'Developer Productivity Tools', prize: '$5,000', description: 'CLI, browser extensions, or workflow automation.' },
    ],
    stages: [
      { id: 'stg_41', eventId: 'evt_4', stageName: '48h Hacking Sprint', stageOrder: 1, startDate: '2026-09-05T00:00:00Z', endDate: '2026-09-07T23:59:59Z', description: 'Ship code & live preview URL' },
    ],
    faqs: [
      { id: 'faq_41', eventId: 'evt_4', question: 'Do I have to deploy the app?', answer: 'Yes, a live working URL is mandatory for evaluation.', createdAt: '2026-08-10T12:00:00Z' },
    ],
    sponsors: [{ name: 'Vercel', tier: 'Partner', logoText: 'VERCEL' }],
  },
  {
    id: 'evt_5',
    organizerId: 'org_5',
    organizerName: 'RoboTech & IoT Guild',
    organizerAvatar: '🤖',
    title: 'Autonomous Robotics & Edge AI Hack',
    slug: 'robotics-edge-ai-hack',
    description:
      'Bridge hardware, computer vision, and ROS2 to create autonomous navigation, drone swarm coordination, and robotic arm manipulation algorithms.',
    category: EventCategory.HACKATHON,
    eventType: EventType.OFFLINE,
    startDate: '2026-09-25T08:00:00Z',
    endDate: '2026-09-27T20:00:00Z',
    registrationDeadline: '2026-09-18T23:59:59Z',
    eligibilityRules: { hardwareProvided: true },
    prizes: [
      { position: '🥇 Best Autonomous System', amount: 30000, description: 'Cash + Jetson Orin Hardware Kit' },
      { position: '🥈 Runner Up', amount: 15000, description: 'Cash + Raspberry Pi 5 Kits' },
    ],
    totalPrizeValue: 45000,
    bannerUrl: null,
    rulesDocUrl: null,
    status: EventStatus.PUBLISHED,
    maxParticipants: 500,
    minTeamSize: 2,
    maxTeamSize: 4,
    isTeamEvent: true,
    location: 'Silicon Valley MakerLab, San Francisco, CA',
    createdAt: '2026-08-12T10:00:00Z',
    participantsCount: 380,
    featured: false,
    tags: ['Robotics', 'ROS2', 'Computer Vision', 'C++', 'Python'],
    bannerGradient: 'from-amber-950/70 via-orange-950/80 to-black',
    tracks: [
      { title: 'Drone Obstacle Evasion', prize: '$15,000', description: 'Real-time LiDAR point cloud trajectory calculation.' },
      { title: 'Precision Pick & Place', prize: '$15,000', description: 'Inverse kinematics with visual feedback.' },
    ],
    stages: [
      { id: 'stg_51', eventId: 'evt_5', stageName: 'Onsite Hacking', stageOrder: 1, startDate: '2026-09-25T08:00:00Z', endDate: '2026-09-27T20:00:00Z', description: '48 hours in the maker lab with physical rigs' },
    ],
    faqs: [
      { id: 'faq_51', eventId: 'evt_5', question: 'Are hardware kits provided?', answer: 'Yes! Jetson boards, cameras, sensors, and basic robotic chassis are provided to all teams.', createdAt: '2026-08-12T10:00:00Z' },
    ],
    sponsors: [{ name: 'NVIDIA', tier: 'Gold Partner', logoText: 'NVIDIA' }],
  },
  {
    id: 'evt_6',
    organizerId: 'org_6',
    organizerName: 'Algorithmic Masters',
    organizerAvatar: '⚡',
    title: 'CodeSprint Global Algorithmic Showdown',
    slug: 'codesprint-algo-showdown-2026',
    description:
      'High-speed competitive programming arena. Solve complex graph theory, dynamic programming, and streaming data challenges within tight memory and time limits.',
    category: EventCategory.QUIZ,
    eventType: EventType.ONLINE,
    startDate: '2026-08-30T14:00:00Z',
    endDate: '2026-08-30T18:00:00Z',
    registrationDeadline: '2026-08-29T23:59:59Z',
    eligibilityRules: null,
    prizes: [
      { position: '🥇 Top Coder', amount: 5000, description: 'Cash + FAANG interview referral' },
      { position: '🥈 Rank 2-5', amount: 1000, description: 'Cash grant each' },
      { position: '🥉 Rank 6-20', amount: 200, description: 'Amazon Gift Card' },
    ],
    totalPrizeValue: 12000,
    bannerUrl: null,
    rulesDocUrl: null,
    status: EventStatus.PUBLISHED,
    maxParticipants: 10000,
    minTeamSize: 1,
    maxTeamSize: 1,
    isTeamEvent: false,
    location: 'Online Judge Arena',
    createdAt: '2026-08-14T09:00:00Z',
    participantsCount: 4890,
    featured: false,
    tags: ['Algorithms', 'C++', 'Python', 'Competitive Coding', 'Data Structures'],
    bannerGradient: 'from-red-950/70 via-rose-950/80 to-black',
    tracks: [{ title: 'Individual Speed Solving', prize: '$12,000 Pool', description: '6 hard algorithmic problems in 4 hours.' }],
    stages: [{ id: 'stg_61', eventId: 'evt_6', stageName: '4h Live Contest', stageOrder: 1, startDate: '2026-08-30T14:00:00Z', endDate: '2026-08-30T18:00:00Z', description: 'Live automated test evaluation' }],
    faqs: [{ id: 'faq_61', eventId: 'evt_6', question: 'Which languages are supported?', answer: 'C++20, Python 3.12, Java 21, Rust 1.80, and Go 1.23.', createdAt: '2026-08-14T09:00:00Z' }],
    sponsors: [{ name: 'HackerRank', tier: 'Platform Partner', logoText: 'HACKERRANK' }],
  },
];

export const MOCK_HACKERS: ExtendedHacker[] = [
  {
    id: 'usr_1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 98765 43210',
    role: UserRole.PARTICIPANT,
    title: 'AI/ML & Systems Engineer',
    college: 'IIT Bombay',
    organization: 'NeuralLab',
    graduationYear: 2026,
    bio: 'Building autonomous agent workflows and distributed LLM fine-tuning pipelines. Winner of ETHIndia 2025.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    skills: ['Python', 'PyTorch', 'Rust', 'LangChain', 'Next.js', 'FastAPI'],
    resumeUrl: null,
    socialLinks: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
      twitter: 'https://x.com',
      portfolio: 'https://aarav.dev',
    },
    emailVerified: true,
    createdAt: '2026-01-15T00:00:00Z',
    rating: 2180,
    hackathonsWon: 6,
    openForTeams: true,
    interests: ['Autonomous Agents', 'Multimodal AI', 'Distributed Systems'],
  },
  {
    id: 'usr_2',
    name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    phone: null,
    role: UserRole.PARTICIPANT,
    title: 'Full-Stack & UI/UX Architect',
    college: 'Stanford University',
    organization: 'Freelance',
    graduationYear: 2025,
    bio: 'Obsessed with fluid micro-interactions, WebGL shaders, TailwindCSS, and Next.js 16. Fast prototype shipper.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    skills: ['TypeScript', 'Next.js', 'React', 'TailwindCSS', 'Three.js', 'Figma'],
    resumeUrl: null,
    socialLinks: {
      github: 'https://github.com',
      twitter: 'https://x.com',
      portfolio: 'https://elena.design',
    },
    emailVerified: true,
    createdAt: '2026-02-10T00:00:00Z',
    rating: 2050,
    hackathonsWon: 4,
    openForTeams: true,
    interests: ['Design Systems', 'Generative UI', 'Creative Coding'],
  },
  {
    id: 'usr_3',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@example.com',
    phone: null,
    role: UserRole.PARTICIPANT,
    title: 'Smart Contract & ZK Researcher',
    college: 'BITS Pilani',
    organization: 'Web3 Ventures',
    graduationYear: 2026,
    bio: 'Writing Circom circuits, Solidity gas-optimized contracts, and Cairo rollups. Looking for backend/frontend wizards.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    skills: ['Solidity', 'Rust', 'Circom', 'Foundry', 'Go', 'Ethereum'],
    resumeUrl: null,
    socialLinks: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    emailVerified: true,
    createdAt: '2026-03-01T00:00:00Z',
    rating: 2310,
    hackathonsWon: 8,
    openForTeams: true,
    interests: ['ZK-Rollups', 'Cross-chain Bridges', 'DeFi Primitives'],
  },
  {
    id: 'usr_4',
    name: 'Mei Lin',
    email: 'mei.lin@example.com',
    phone: null,
    role: UserRole.PARTICIPANT,
    title: 'Robotics & Embedded Systems Hacker',
    college: 'NUS Singapore',
    organization: 'RoboLab',
    graduationYear: 2026,
    bio: 'ROS2 navigation, SLAM algorithms, and edge neural processing on Jetson. Building autonomous swarm drones.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    skills: ['C++', 'Python', 'ROS2', 'OpenCV', 'CUDA', 'Docker'],
    resumeUrl: null,
    socialLinks: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    emailVerified: true,
    createdAt: '2026-04-12T00:00:00Z',
    rating: 1980,
    hackathonsWon: 3,
    openForTeams: true,
    interests: ['Drone Swarms', 'Edge AI', 'Computer Vision'],
  },
  {
    id: 'usr_5',
    name: 'Marcus Vance',
    email: 'marcus.vance@example.com',
    phone: null,
    role: UserRole.PARTICIPANT,
    title: 'Cloud Architect & DevOps Specialist',
    college: 'MIT',
    organization: 'Vance Scale',
    graduationYear: 2025,
    bio: 'Kubernetes, Terraform, event-driven streaming with Kafka, and zero-downtime infra deployments.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    skills: ['Kubernetes', 'Go', 'AWS', 'PostgreSQL', 'Kafka', 'Terraform'],
    resumeUrl: null,
    socialLinks: {
      github: 'https://github.com',
    },
    emailVerified: true,
    createdAt: '2026-05-18T00:00:00Z',
    rating: 2120,
    hackathonsWon: 5,
    openForTeams: false,
    interests: ['Distributed Databases', 'High-concurrency APIs', 'Fintech Infra'],
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, name: 'Vikramaditya Rao', university: 'BITS Pilani', score: 9850, won: 8, badge: '🏆 Grandmaster' },
  { rank: 2, name: 'Aarav Sharma', university: 'IIT Bombay', score: 9240, won: 6, badge: '⚡ Master Builder' },
  { rank: 3, name: 'Sophia Zhang', university: 'UC Berkeley', score: 8900, won: 5, badge: '⚡ Master Builder' },
  { rank: 4, name: 'Marcus Vance', university: 'MIT', score: 8450, won: 5, badge: '💎 Veteran' },
  { rank: 5, name: 'Elena Rostova', university: 'Stanford', score: 8120, won: 4, badge: '💎 Veteran' },
  { rank: 6, name: 'Devon Walker', university: 'Waterloo', score: 7890, won: 4, badge: '🔥 Elite Hacker' },
  { rank: 7, name: 'Mei Lin', university: 'NUS Singapore', score: 7600, won: 3, badge: '🔥 Elite Hacker' },
  { rank: 8, name: 'Aditya Verma', university: 'IIIT Hyderabad', score: 7350, won: 3, badge: '🔥 Elite Hacker' },
];

export const MOCK_COLLEGES = [
  { rank: 1, name: 'IIT Bombay', country: '🇮🇳 India', builders: 1420, wins: 48, points: 42300 },
  { rank: 2, name: 'Stanford University', country: '🇺🇸 USA', builders: 1180, wins: 42, points: 39800 },
  { rank: 3, name: 'BITS Pilani', country: '🇮🇳 India', builders: 980, wins: 36, points: 34500 },
  { rank: 4, name: 'MIT', country: '🇺🇸 USA', builders: 940, wins: 35, points: 33900 },
  { rank: 5, name: 'University of Waterloo', country: '🇨🇦 Canada', builders: 890, wins: 31, points: 30200 },
  { rank: 6, name: 'NUS Singapore', country: '🇸🇬 Singapore', builders: 760, wins: 28, points: 27800 },
];
